import { Dream, Symbol } from "./types";

export const mockSymbols: Symbol[] = [
  { id: "s1", name: "Flying", frequency: 12 },
  { id: "s2", name: "Ocean", frequency: 8 },
  { id: "s3", name: "City", frequency: 6 },
  { id: "s4", name: "Forest", frequency: 9 },
  { id: "s5", name: "School", frequency: 5 },
  { id: "s6", name: "Running", frequency: 7 },
  { id: "s7", name: "Light", frequency: 10 },
  { id: "s8", name: "Mountain", frequency: 4 },
  { id: "s9", name: "Mirror", frequency: 3 },
  { id: "s10", name: "Rain", frequency: 6 },
  { id: "s11", name: "Door", frequency: 5 },
  { id: "s12", name: "Stars", frequency: 8 },
];

export const mockDreams: Dream[] = [
  {
    id: "d1",
    title: "The Glass City Above the Sea",
    description: "I was flying above a purple ocean and saw a floating glass city. The buildings shimmered with an inner light, and I could hear distant music echoing across the waves. As I descended, the city seemed to breathe, its walls expanding and contracting like a living organism.",
    date: "2026-03-03",
    generated_image: "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=800&q=80",
    emotion: "Wonder",
    symbols: ["Flying", "Ocean", "City", "Light"],
    themes: ["Exploration", "Freedom", "Discovery"],
  },
  {
    id: "d2",
    title: "The Endless Forest Path",
    description: "Walking through an ancient forest where the trees whispered secrets. Each tree had a door carved into its trunk, and behind each door was a different memory from my childhood. The deeper I went, the younger the memories became.",
    date: "2026-03-01",
    generated_image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
    emotion: "Nostalgia",
    symbols: ["Forest", "Door", "Light"],
    themes: ["Memory", "Growth", "Identity"],
  },
  {
    id: "d3",
    title: "Running Through Starlight",
    description: "I was running across a vast plain where the ground was made of mirrors reflecting the night sky. Every step created ripples of starlight. I was chasing something I couldn't see but deeply needed to find.",
    date: "2026-02-27",
    generated_image: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&q=80",
    emotion: "Urgency",
    symbols: ["Running", "Stars", "Mirror"],
    themes: ["Purpose", "Search", "Transcendence"],
  },
  {
    id: "d4",
    title: "The Mountain That Sang",
    description: "A mountain rose from the ocean, and as waves crashed against it, the stone produced deep harmonic sounds. I climbed it barefoot, each ledge playing a different note. At the summit, I could see the curvature of the Earth.",
    date: "2026-02-24",
    generated_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    emotion: "Awe",
    symbols: ["Mountain", "Ocean", "Light"],
    themes: ["Achievement", "Perspective", "Harmony"],
  },
  {
    id: "d5",
    title: "Rain in the Classroom",
    description: "I was back in school but it was raining inside the classroom. Each raindrop contained a tiny scene from the future. My old teacher pointed at the rain and said 'these are all the lives you could live.'",
    date: "2026-02-20",
    generated_image: "https://images.unsplash.com/photo-1428592953211-077101b2021b?w=800&q=80",
    emotion: "Melancholy",
    symbols: ["Rain", "School", "Light"],
    themes: ["Possibility", "Time", "Choice"],
  },
  {
    id: "d6",
    title: "The City of Doors",
    description: "An infinite city where every wall was a door. Opening one would close another somewhere else. I spent what felt like years navigating the labyrinth, searching for the one door that led outside. When I found it, it opened onto a calm ocean at dawn.",
    date: "2026-02-16",
    generated_image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800&q=80",
    emotion: "Determination",
    symbols: ["City", "Door", "Ocean"],
    themes: ["Persistence", "Freedom", "Transition"],
  },
];
